server:
  port: ${PORT:8002}
  servlet:
    context-path: /catalog/

spring:
  sleuth:
    sampler:
		  probability: 1.0
  rabbitmq:
    addresses:localhost:5672
    virtual-host: app_vhost
    username:username
    password:password
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type:rabbit
    enabled:true

  data
    mongodb
      authentication-database: admin
      username: root
      password: root
      database: test_db
      port: 27017
      host: localhost

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

message: Hello from Catalog Server

management:
  endpoints:
    web:
      exposure:
        include: '*'