server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: moviesRoute
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**